[package]
name = "quiz"
version = "0.1.0"
edition = "2024"

[dependencies]
ron = "0.11.0"
serde = { version = "1.0.219", features = ["derive"] }
dialoguer = "0.12.0"
console = "0.16.0"
thiserror = "2.0.16"
clap = { version = "4.5.45", features = ["derive"] }
